finite_finite:
    sylius_payment:
        class:         %sylius.model.payment.class%
        property_path: state
        graph:         sylius_payment
        states:
            new:
                type: initial
            unknown:    ~
            pending:    ~
            processing: ~
            completed:  ~
            failed:
                type: final
            cancelled:  ~
            void:
                type: final
            refunded:
                type: final
        transitions:
            create:
                from: [new]
                to:   pending
            process:
                from: [new, pending]
                to:   processing
            complete:
                from: [new, pending, processing]
                to:   completed
            fail:
                from: [new, pending, processing]
                to:   failed
            cancel:
                from: [new, pending, processing]
                to:   cancelled
            refund:
                from: [completed]
                to:   refunded
            void:
                from: [new, pending]
                to:   void
