# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

imports:
    - { resource: "@SyliusPaymentBundle/Resources/config/app/messenger.yaml" }

jms_serializer:
    metadata:
        directories:
            sylius-payment:
                namespace_prefix: "Sylius\\Component\\Payment"
                path: "@SyliusPaymentBundle/Resources/config/serializer"

sylius_payment:
    payment_request:
        states_that_should_be_cancelled_when_payment_request_has_changed:
            - !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::STATE_PROCESSING
            - !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::STATE_NEW
