# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

imports:
    - { resource: "@SyliusPaymentBundle/Resources/config/app/messenger.yaml" }
    - { resource: "@SyliusPaymentBundle/Resources/config/app/state_machine.yml" }
    - { resource: "@SyliusPaymentBundle/Resources/config/app/workflow.yaml" }

jms_serializer:
    metadata:
        directories:
            sylius-payment:
                namespace_prefix: "Sylius\\Component\\Payment"
                path: "@SyliusPaymentBundle/Resources/config/serializer"
