sylius_webhook_payment_method:
    path: /payment-method/{code}
    defaults:
        _controller: sylius.action.webhook_payment_request

sylius_shop_webhook_payment_request:
    path: /payment-request/{hash}
    defaults:
        _controller: sylius.action.webhook_payment_method
