sylius_payment_method_notify:
    path: /payment-method/{code}
    defaults:
        _controller: sylius.controller.payment_request_notify

sylius_payment_request_notify:
    path: /payment-request/{hash}
    defaults:
        _controller: sylius.controller.payment_method_notify
