Sylius\Component\Payment\Model\Payment:
    exclusion_policy: ALL
    xml_root_name: payment
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        amount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        currency:
            expose: true
            type: string
            groups: [Default, Detailed]
        state:
            expose: true
            type: string
            groups: [Default, Detailed]
        method:
            expose: true
            groups: [Default, Detailed]
    relations:
        - rel: self
          exclusion:
                exclude_if: expr(!object.getId())
          href:
                route: sylius_api_payment_show
                parameters:
                    id: expr(object.getId())
                    version: 1
        - rel: payment-method
          exclusion:
                exclude_if: expr(!object.getMethod())
          href:
                route: sylius_api_payment_method_show
                parameters:
                    code: expr(object.getMethod().getCode())
                    version: 1
