Sylius\Component\Payment\Model\PaymentMethod:
    exclusion_policy: ALL
    xml_root_name: payment-method
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        name:
            expose: true
            type: string
            groups: [Default, Detailed]
    relations:
        - rel: self
          href:
                route: sylius_api_payment_method_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
